PYTHON = python3
SRC = sokoban.py

r:
	$(PYTHON) sokoban.py 1 ucs

d:
	$(PYTHON) sokoban.py 1 ucs -d

f:
	$(PYTHON) sokoban.py 1 f

a:
	$(PYTHON) sokoban.py 1 a

all:
	$(PYTHON) sokoban.py 1 fa -d
	$(PYTHON) sokoban.py 2 fa -d
	$(PYTHON) sokoban.py 3 fa -d
	$(PYTHON) sokoban.py 4 fa -d
	$(PYTHON) sokoban.py 5 fa -d
	$(PYTHON) sokoban.py 6 fa -d
	$(PYTHON) sokoban.py 7 fa -d
	$(PYTHON) sokoban.py 8 fa -d
	$(PYTHON) sokoban.py 9 fa -d
	$(PYTHON) sokoban.py 10 fa -d
	$(PYTHON) sokoban.py 11 fa -d
	$(PYTHON) sokoban.py 12 fa -d
	$(PYTHON) sokoban.py 13 fa -d
